services:
- type: web
  name: thivlevel-nextjs-app
  runtime: node
  plan: starter
  buildCommand: npm run build
  startCommand: npm run start
  autoDeploy: false
  envVars:
  - key: NODE_ENV
    value: production