interface Product {
    images: ImageObject[],
    size: string[],
    colors: string[],
    checked: boolean,
    sold: number,
    rating: number,
    numReviews: number,
    countInStock: number,
    isPublished: boolean,
    _id: string,
    product_id: string,
    title: string,
    description: string,
    content: string,
    price: number,
    category: string,
    reviews: Review[],
    createdAt: string,
    updatedAt: string,
    __v: number,
}